apiVersion: v1
kind: ServiceAccount
metadata:
  name: observador
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leitor-pods
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - TODO_VERBOS
- apiGroups:
  - ''
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observador-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leitor-pods
subjects:
- kind: ServiceAccount
  name: observador
